### ISSUE TITLE
[README] the list of supported authentication schemes is missing

### ISSUE THREAD

**Issue by dodikk** [jivesoftware/JiveAuthenticatingHTTPProtocol#4]
According to the demo app, the library supports `BASIC` authentication scheme.
The "readme" page neither mentions that, nor tells about other schemes support.

What is the state of the listed ones ?
* DIGEST
* NTLM
* ADFS
* Other common schemes http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml

**Comment by hborders** [comment]
This library supports all of the authentication schemes `NSURLAuthentication` supports.

**Comment by hborders** [comment]
This has been tested with NTLM and ADFS authentication, (which `NSURLAuthentication` natively supports). Basically, if an authentication method works in Safari, it'll probably work here, too.

**Comment by dodikk** [comment]
Thanks for the reply. I was asking since I tried to connect via ADFS but failed. My mistake was incorrect stubbing of the `canAuthenticateAgainstProtectionSpace:` method.

# Incorrect code: 
```obj-c
- (BOOL)authenticatingHTTPProtocol:(JAHPAuthenticatingHTTPProtocol *)authenticatingHTTPProtocol
canAuthenticateAgainstProtectionSpace:(NSURLProtectionSpace *)protectionSpace
{
    // that's not correct
    return true;
}
```

As the result, I saw some `OAuth` related redirects in the logs and the desired page has not loaded properly.


# Fixed code :
```obj-c
- (BOOL)authenticatingHTTPProtocol:(JAHPAuthenticatingHTTPProtocol *)authenticatingHTTPProtocol
canAuthenticateAgainstProtectionSpace:(NSURLProtectionSpace *)protectionSpace
{
    NSArray* interceptedAuthMethods =
    @[
      NSURLAuthenticationMethodHTTPBasic
      , NSURLAuthenticationMethodNTLM
    ];
    
    NSSet* interceptedAuthMethodsSet = [NSSet setWithArray: interceptedAuthMethods];
    
    BOOL canAuthenticate =
        [interceptedAuthMethodsSet containsObject: protectionSpace.authenticationMethod];
    
    return canAuthenticate;
}
```

P.S. I hope that helps if someone runs into similar problems.

**Comment by dodikk** [comment]
@hborders , thank you for fast replies and for sharing this library.

**Comment by dodikk** [comment]
Added some info from this discussion to the readme via https://github.com/jivesoftware/JiveAuthenticatingHTTPProtocol/pull/7
