### ISSUE TITLE
[readme] [question] please describe the extension points to add support for more authorization schemes

### ISSUE THREAD

**Issue by dodikk** [jivesoftware/JiveAuthenticatingHTTPProtocol#5]
What are the library's extension points for the non-`BASIC` schemes? 
I need to implement a different scheme and I want to send a Pull Reqest when I get it done . 
What's the best method to start looking at?

**Comment by hborders** [comment]
This library supports all of the authentication schemes `NSURLAuthentication` supports. If `NSURLAuthentication` has extension points, then perhaps you can use those for non-standard schemes.

**Comment by dodikk** [comment]
Added some info from this discussion to the readme via https://github.com/jivesoftware/JiveAuthenticatingHTTPProtocol/pull/7
